=null)s=a.a>=a.b&&a.c>=a.d
else s=!0
if(s)return new A.A(A.x(0,a.a,a.b),A.x(0,a.c,a.d))
p=p.ad(B.I,a,p.gbX())
switch(q.e_.a){case 0:return a.aQ(p)
case 1:if(!J.c(q.by.b,p))return a.aQ(q.gt())
else{s=q.b6
s===$&&A.a()
r=s.x
r===$&&A.a()
if(r===s.b)return a.aQ(p)}break
case 3:case 2:if(!J.c(q.by.b,p))return a.aQ(p)
break}p=q.c1
p===$&&A.a()
p=q.by.a1(p.gm())
p.toString
return a.aQ(p)},
Wz(a){},
av(a,b){var s,r,q,p=this
if(p.q$!=null){s=p.du
s===$&&A.a()
s=s&&p.lT!==B.o}else s=!1
r=p.O7
if(s){s=p.gt()
q=p.cx
q===$&&A.a()
r.sag(a.kY(q,b,new A.r(0,0,0+s.a,0+s.b),A.np.prototype.ge7.call(p),p.lT,r.a))}else{r.sag(null)
p.TI(a,b)}},
l(){var s,r=this
r.O7.sag(null)
s=r.b6
s===$&&A.a()
s.l()
s=r.c1
s===$&&A.a()
s.l()
r.fe()}}
A.a1T.prototype={
$0(){var s=this.a,r=s.b6
r===$&&A.a()
r=r.x
r===$&&A.a()
if(r!==s.cB)s.X()},
$S:0}
A.wH.prototype={
gwC(){var s,r=this,q=r.ax$
if(q===$){s=A.av2(new A.a2y(r),new A.a2z(r),new A.a2A(r))
q!==$&&A.ag()
r.ax$=s
q=s}return q},
CB(){var s,r,q,p,o,n,m,l,k,j,i
for(s=this.CW$.gaV(),r=A.m(s),s=new A.br(J.aJ(s.a),s.b,r.j("br<1,2>")),r=r.y[1],q=!1;s.v();){p=s.a
if(p==null)p=r.a(p)
q=q||p.q$!=null
o=p.go
n=$.cF()
m=n.d
if(m==null){l=self.window.devicePixelRatio
m=l===0?1:l}l=o.at
if(l==null){l=o.ch.Bt()
o.at=l}l=A.amz(o.Q,new A.A(l.a/m,l.b/m))
o=l.a*m
k=l.b*m
j=l.c*m
l=l.d*m
i=n.d
if(i==null){n=self.window.devicePixelRatio
i=n===0?1:n}p.suY(new A.yj(new A.a8(o/i,k/i,j/i,l/i),new A.a8(o,k,j,l),i))}if(q)this.Rv